
name: Build and Test

on:
  pull_request:
    branches: 
      - main
  workflow_call:

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 20 ]

    name: Node ${{ matrix.node }} sample
    steps:
      - uses: actions/checkout@v4
      - name: Building rules and tests
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - run: npm ci
      - run: npm run build
      - run: npm run test-ci
