name: Build Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch: 
  
permissions:
  contents: write
  pages: write
  id-token: write
  packages: write

jobs:
  publish:
    uses: ./.github/workflows/publish.yml
    if: github.ref_type == 'tag'

  build-linux:
    uses: ./.github/workflows/build-linux.yml
    
  build-windows:
    uses: ./.github/workflows/build-windows.yml
    
  build-macos:
    uses: ./.github/workflows/build-macos.yml

  build-publish-docker:
    uses: ./.github/workflows/build-publish-docker.yml
    needs: [publish, build-linux, build-windows, build-macos]

  release:
    runs-on: ubuntu-latest
    if: github.ref_type == 'tag'
    needs: [build-publish-docker]
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - run: tar -czf mssql-proxy-${{ github.ref_name }}-source.tar.gz Tools/mssql-proxy
    - uses: actions/download-artifact@v4
      with:
        pattern: build-*
        path: ./
        merge-multiple: true
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        prerelease: true
        generate_release_notes: true
        files: |
          mssql-proxy-${{ github.ref_name }}-source.tar.gz
          mssql-proxy-${{ github.ref_name }}-windows.zip
          mssql-proxy-${{ github.ref_name }}-linux-amd64.tar.gz
          mssql-proxy-${{ github.ref_name }}-linux-arm64.tar.gz
          mssql-proxy-${{ github.ref_name }}-macos.tar.gz