name: Build Binaries

on:
  workflow_call:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['windows-latest', 'ubuntu-latest']

    steps:
    - uses: actions/checkout@v4.2.2
    - uses: actions/setup-python@v5.3.0
      with:
        python-version: 3.11.4
    - run: pip install -r CodeChefDatabaseProxy/requirements.txt pyinstaller
    - run: pyinstaller --onefile proxy.py
      working-directory: CodeChefDatabaseProxy
    # Optionally verify that it works (provided that it does not need user interaction)
    #- run: ./dist/your-code/your-code
    - uses: actions/upload-artifact@v4.4.3
      with:
        path: CodeChefDatabaseProxy/dist/*
