name: Build Binaries

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: ['windows-latest', 'ubuntu-latest']

    steps:
    - uses: actions/checkout@v4.2.2
    - uses: actions/setup-python@v5.3.0
      with:
        python-version: 3.11.4
    - run: pip install -r CodeChefDatabaseProxy/requirements.txt pyinstaller
    - run: pyinstaller --onefile proxy.py
      working-directory: CodeChefDatabaseProxy
    - uses: montudor/action-zip@v1.0.0
      with:
        args: zip -qq -r proxy.zip CodeChefDatabaseProxy/dist
    - uses: actions/upload-release-asset@v1
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
        asset_path: CodeChefDatabaseProxy/dist/proxy.zip
        asset_name: proxy-${{ matrix.os }}.zip
        asset_content_type: application/zip
