name: Build MacOS

on:
  workflow_call:
  workflow_dispatch: 
  
jobs:
  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: 3.11.4
    
    - name: Install Homebrew
      run: |
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"   

    - name: Install UnixODBC and MSODBCSQL18
      run: |
        brew install unixodbc msodbcsql18

    - run: pip install -r Tools/mssql-proxy/requirements.txt pyinstaller
    - run: pyinstaller mssql-proxy.mac.spec
      working-directory: Tools/mssql-proxy
    - run: tar -czf mssql-proxy-${{ github.ref_name }}-macos.tar.gz Tools/mssql-proxy/dist
    - uses: actions/upload-artifact@v4
      with:
        name: build-macos
        path: mssql-proxy-${{ github.ref_name }}-macos.tar.gz
   