name: Create Publish

on:
  workflow_call:
  workflow_dispatch: 

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  tests:
    uses: ./.github/workflows/build-test.yml

  deploy:
    needs: [tests]
    environment:
      name: "github-pages"
      url: ${{ steps.build-publish.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
    - id: build-publish
      uses: bitovi/github-actions-angular-to-github-pages@v1.0.0
      with:
        path: dist/code-chef/browser
        build_command: npm run build
