
name: Build Test

on:
  pull_request:
    branches: 
      - main
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 20 ]

    name: Node ${{ matrix.node }} sample
    steps:
      - uses: actions/checkout@v4
      - name: Building rules and tests
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - run: npm ci
        working-directory: Frontend
      - run: npm run test-ci
        working-directory: Frontend
      - run: npm run build
        working-directory: Frontend
      - uses: actions/upload-artifact@v4
        if: github.event_name != 'pull_request'
        with:
          name: codechef-build
          path: Frontend/dist/code-chef
